In [1]:
import numpy as np

##### array
- ndim : 행렬의 차원
- shape: 행렬의 모양

In [3]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [6]:
# 2차원 배열
array = np.array([[0],[1],[2]])
print(array)

[[0]
 [1]
 [2]]


In [7]:
array = np.array([
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]],
    
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]]
])
print(array)
print(array.ndim, array.shape) # 바깥에서 안으로의 모양

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
3 (2, 3, 4)


#### reshape
- 행렬의 모양 바꿀 수 있다.

In [8]:
na = np.array([1,2,3,4,5,6,7,8])
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
na.reshape((2,4)) # 2 X 4 matrix change

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
rna = np.reshape(na, (4,2)) # 4 X 2 matrix change
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
# 전치행렬
rna.T # 2 X 4 matrix change

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

#### index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기

In [13]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [14]:
print(array[1][1][2])
print(array[1,1,2])

6
6


In [15]:
result = array[1:,1:,2:]
print(result)
print(result.ndim, result.shape)

[[[ 6  7]
  [10 11]]]
3 (1, 2, 2)


In [20]:
result[0].ndim

2

In [21]:
# 데이터 수정
data = np.zeros(5, dtype=int)
data

array([0, 0, 0, 0, 0])

In [24]:
data[1] = 1
data

array([0, 1, 0, 0, 0])

In [26]:
data[3:] = 2
data

array([0, 1, 0, 2, 2])

In [27]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
z[1:,2:] = 2
z

array([[0., 0., 0., 0.],
       [0., 0., 2., 2.],
       [0., 0., 2., 2.]])

#### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [31]:
z = np.zeros((2,3,4))
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [32]:
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


#### eye
- 단위행렬 데이터를 만든다

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀 수 있다.

In [34]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
ls_1 = np.zeros_like(o)
print(ls_1)
print(ls_1.ndim, ls_1.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


In [40]:
ls_2 = np.ones_like(z)
print(ls_2)
print((ls_2.ndim, ls_2.shape))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(3, (2, 3, 4))


#### empty
- 빈 행렬을 만든다
- 실제로는 빈데이터가 아니라 더미 데이터로 들어간다.

In [42]:
a = np.empty((5,5))
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
b = np.empty((6,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### arange
- range와 같다.
- 하지만 큰 데이터에서 range보다 속도가 빠르다.

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [46]:
np.arange(2,10,3)

array([2, 5, 8])

In [47]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

#### linspace & logspace

In [48]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [50]:
# 2~4까지 3개로 나누기
# logx = 2, 3, 4이 되도록 하는 x값을 출력하라
print(np.logspace(2,4,3)) 

[  100.  1000. 10000.]


In [54]:
print(np.logspace(1,4,4))

[   10.   100.  1000. 10000.]


##### random
- seed
- rand (uniform)
- randn (gaussian)
- randint
- shuffle
- choice

In [64]:
np.random.seed(0)
rd = np.random.rand(10)
rdn = np.random.randn(10)
print(rd)
print(rdn)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [68]:
r = np.random.rand(2,3,4)
r

array([[[0.73926358, 0.03918779, 0.28280696, 0.12019656],
        [0.2961402 , 0.11872772, 0.31798318, 0.41426299],
        [0.0641475 , 0.69247212, 0.56660145, 0.26538949]],

       [[0.52324805, 0.09394051, 0.5759465 , 0.9292962 ],
        [0.31856895, 0.66741038, 0.13179786, 0.7163272 ],
        [0.28940609, 0.18319136, 0.58651293, 0.02010755]]])

In [70]:
# 지정된 범위의 수로 행렬 만들기
r = np.random.randint(5, 10, (3,3))
r

array([[8, 5, 7],
       [7, 5, 9],
       [8, 9, 5]])

In [72]:
# 시작과 끝을 모두 안적어주는 경우 : range와 비슷
r = np.random.randint(10,size=(3,3)) # 10보다 작은 수로 행렬 만들어라
r

array([[0, 9, 6],
       [5, 3, 1],
       [8, 0, 4]])

In [74]:
# shuffle로 데이터 순서 바꾸기
np.random.shuffle(r)
r

array([[8, 0, 4],
       [5, 3, 1],
       [0, 9, 6]])

In [75]:
# p의 확률로 range(5)를 10개 추출
print(list(range(5)))
print([0.1,0,0.3,0.6,0])
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0]) # 0~4중 10개를 각 확률을 바탕으로 추출

[0, 1, 2, 3, 4]
[0.1, 0, 0.3, 0.6, 0]


array([3, 2, 3, 3, 2, 2, 3, 3, 3, 3], dtype=int64)

In [77]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할 수 있다.
index, count = np.unique(r, return_counts=True)
print(index) # unique한 값(중복제거)
print(count) # unique한 값들의 갯수

[0 1 3 4 5 6 8 9]
[2 1 1 1 1 1 1 1]


#### stack
- 행렬을 쌓는 것과 같이 합치는 방법

In [80]:
na1 = np.arange(6)
na2 = np.arange(6,12)
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(2,3))
print(na1, na1.shape)
print(na2, na2.shape)

[[6 5 7]
 [0 8 4]] (2, 3)
[[6 5 8]
 [2 3 9]] (2, 3)


In [81]:
na3 = np.stack((na1,na2))
print(na3, na3.shape)

[[[6 5 7]
  [0 8 4]]

 [[6 5 8]
  [2 3 9]]] (2, 2, 3)


In [82]:
na4 = np.stack((na1,na2), axis=1)
print(na4, na4.shape)

[[[6 5 7]
  [6 5 8]]

 [[0 8 4]
  [2 3 9]]] (2, 2, 3)


In [83]:
na5 = np.stack((na1,na2), axis=2)
print(na5, na5.shape)

[[[6 6]
  [5 5]
  [7 8]]

 [[0 2]
  [8 3]
  [4 9]]] (2, 3, 2)


In [84]:
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [89]:
np.vstack(ls) # 위로 쌓아줌

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [90]:
np.hstack(ls) # 옆으로 쌓아줌(하나의 리스트형태)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [91]:
data = [list(range(7))[i:i+3] for i in range(5)]
print(data)

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


In [96]:
np.stack(data, axis=1) # axis가 커질수록 차원이 안쪽으로 간다.

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

#### concatenate 결합
- 가로결합 : 행의 갯수가 같아야함.
- 세로결합 : 열의 갯수가 같아야함.

In [97]:
r1 = np.random.randint(10, size=(2,3)) #10이하의 숫자로 2X3행렬 만들기
r1

array([[7, 5, 3],
       [4, 5, 3]])

In [98]:
r2 = np.random.randint(10, size=(3,2)) #10이하의 숫자로 3X2행렬 만들기
r2

array([[3, 7],
       [9, 9],
       [9, 7]])

In [99]:
r3 = np.random.randint(10, size=(3,3)) #10이하의 숫자로 3X3행렬 만들기
r3

array([[3, 2, 3],
       [9, 7, 7],
       [5, 1, 2]])

In [100]:
np.concatenate([r1,r3])

array([[7, 5, 3],
       [4, 5, 3],
       [3, 2, 3],
       [9, 7, 7],
       [5, 1, 2]])

In [102]:
np.concatenate([r2,r3], axis=1)

array([[3, 7, 3, 2, 3],
       [9, 9, 9, 7, 7],
       [9, 7, 5, 1, 2]])

#### split

In [103]:
r = np.arange(10)
r # 0앞에서부터 0으로 셈

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
r1 = np.split(r, [5]) # 0앞에서부터 0으로 세서 5번째에서 자름.
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [106]:
r2 = np.split(r, [2,4,6,8])
r2

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [107]:
# vsplit

In [108]:
r = np.random.randint(10, size=(4,6))
r

array([[2, 8, 1, 5, 8, 4],
       [0, 2, 5, 5, 0, 8],
       [1, 1, 0, 3, 8, 8],
       [4, 4, 0, 9, 3, 7]])

In [109]:
np.vsplit(r, [2,3])

[array([[2, 8, 1, 5, 8, 4],
        [0, 2, 5, 5, 0, 8]]),
 array([[1, 1, 0, 3, 8, 8]]),
 array([[4, 4, 0, 9, 3, 7]])]

In [110]:
# hsplit

In [112]:
np.hsplit(r, [2])

[array([[2, 8],
        [0, 2],
        [1, 1],
        [4, 4]]), array([[1, 5, 8, 4],
        [5, 5, 0, 8],
        [0, 3, 8, 8],
        [0, 9, 3, 7]])]

[array([[2, 8, 1, 5, 8, 4],
        [0, 2, 5, 5, 0, 8]]), array([[1, 1, 0, 3, 8, 8],
        [4, 4, 0, 9, 3, 7]])]