#### numpy - calculate
- 기본연산
- 브로드캐스팅
- 함수
- 퍼포먼스

#### 기본연산

In [1]:
ls = [1,2,3]
ls*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
ls = [num*3 for num in ls]
ls

[9, 18, 27]

In [4]:
na = np.array([1,2,3])
na

array([1, 2, 3])

In [5]:
na*3

array([3, 6, 9])

In [7]:
na1 = np.array([1,2,3])
na2 = np.array([4,5,6])
na1 * na2

array([ 4, 10, 18])

In [9]:
# 비교연산
na1 == 2, na2 > 5

(array([False,  True, False]), array([False, False,  True]))

In [12]:
na1 = np.array(range(1,10))
print(na1)
na1 % 3 == 0

[1 2 3 4 5 6 7 8 9]


array([False, False,  True, False, False,  True, False, False,  True])

In [16]:
is3 = na1 % 3 == 0
na1[is3], na1[na1 % 2 == 0] # True값만 뽑기(filtering)

(array([3, 6, 9]), array([2, 4, 6, 8]))

#### 브로드 캐스팅

In [24]:
na1 = np.arange(12)
na2 = np.reshape(na1,(3,4))
na3 = np.ones((3,4), dtype=int)
print(na1)
print(na2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
na2 + na3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
na2 + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
# row에 대한 브로드 캐스팅
na4 = np.arange(4)
print(na4, na4.shape)

[0 1 2 3] (4,)


In [30]:
na4 + na2

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [31]:
# column에 대한 브로드 캐스팅

In [34]:
na5 = np.arange(3)[:, np.newaxis]
na5, na5.shape

(array([[0],
        [1],
        [2]]), (3, 1))

In [35]:
na2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
na2 + na5

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

#### functions
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile
- exp, log

In [38]:
r = np.random.randint(10, size=(2,3))
r, np.random.rand

array([[4, 9, 5],
       [3, 8, 3]])

In [42]:
# argmin(), argmax() : 위치값 출력
r.min(), r.max(), r.argmin(), r.argmax()

(3, 9, 3, 1)

In [45]:
r.mean(), np.sum(r), 

(5.333333333333333, 5.333333333333333)

In [47]:
np.sum(r, axis=0) # 같은 열의 합

array([ 7, 17,  8])

In [49]:
np.sum(r, axis=1) # 같은 행의 합

array([18, 14])

In [52]:
r

array([[4, 9, 5],
       [3, 8, 3]])

In [54]:
np.median(r) # 펼쳤을 때 중앙값

4.5

In [56]:
np.std(r) # 표준편차

2.3570226039551585

In [57]:
np.var(r)

5.555555555555556

In [ ]:
# all : 모든 조건이 충족하면 True : AND의 개념
# any : 하나의 조건만 충족하면 True : OR의 개념

In [59]:
n1 = np.array(range(3,8))
n1

array([3, 4, 5, 6, 7])

In [61]:
n2 = n1
n2

array([3, 4, 5, 6, 7])

In [62]:
n3 = np.array([3,4,0,6,7])
n3

array([3, 4, 0, 6, 7])

In [64]:
np.all(n1 == n2), np.all(n1 == n3)

(True, False)

In [67]:
n4 = np.array(range(10,15))
np.any(n1 == n2), np.any(n1 == n3), np.any(n4 == n1)

(True, True, False)

In [71]:
# 사분위수
na = np.arange(100, 201)
print(na)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [73]:
np.percentile(na, 25), np.percentile(na, 62)

(125.0, 162.0)

In [74]:
# 지수함수 : 작은 수치의 데이터 스케일을 키울 때 주로 사용
na = np.arange(1,6)
na

array([1, 2, 3, 4, 5])

In [76]:
np.exp(na)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [78]:
# 로그함수 : 큰 수치의 데이터 스케일을 줄일 때 주로 사용
na = np.arange(1,6)
np.log(na)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

#### 성능확인

In [79]:
# 10 ** 7개의 리스트에서 3과 5의 배수의 갯수를 찾는시간

In [85]:
%%time
ls = []
size = int(10E7)
for data in range(size):
    ls.append(data)
len(ls)

Wall time: 32.3 s


In [86]:
%%time
la = np.arange(size)
len(la)

Wall time: 327 ms


In [87]:
%%time
count = 0
for idx in range(len(ls)):
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
print(count) 

46666667
Wall time: 38.9 s


In [88]:
%%time
count = len(la[(la % 3 == 0 | (la % 5 == 0))])
count

Wall time: 3.75 s
