### axis가 중요하다!!

In [4]:
# 2차원
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a.sum(axis=1), a.sum(axis=0), a.sum()

(array([10, 26, 42]), array([15, 18, 21, 24]), 78)

In [7]:
b = np.array([a,a,a])
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [9]:
b.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [10]:
b.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [12]:
b.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [14]:
# mathematical function
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [15]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

### concatenate

In [30]:
# stack
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((x,y))

array([[1, 2, 3],
       [2, 3, 4]])

In [23]:
v = np.array([[1],[2],[3]])
w = np.array([[2],[3],[4]])
np.hstack((v,w))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [25]:
x = np.array([1,2,3])
y = np.array([2,3,4])
np.hstack((x,y))

array([1, 2, 3, 2, 3, 4])

In [32]:
# concatenate
np.concatenate((a,b), axis=0)

array([1, 2, 3, 2, 3, 4])

In [34]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6],[4,5,6]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [35]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6],[4,5,6]])
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])