In [2]:
a = np.random.randint(9,21,size=(15,9))
a

array([[10, 14,  9, 10, 11, 15, 17, 10, 10],
       [13, 17, 10, 14, 18, 19, 12,  9,  9],
       [10, 16, 11, 11,  9, 14, 17, 13,  9],
       [18, 15, 18, 16, 11, 18, 14, 15, 19],
       [19,  9, 11, 19, 15, 20, 12, 12, 18],
       [14, 11, 17, 17, 14, 11, 13, 15, 17],
       [20,  9,  9,  9, 11, 19, 13,  9, 10],
       [17, 19, 12, 14, 17, 19, 20, 16, 10],
       [12,  9, 18, 17, 10, 13, 12, 10, 20],
       [17, 13, 12, 15, 13,  9, 14, 17, 18],
       [19, 17, 11, 10, 20, 12,  9, 15, 17],
       [20, 16, 12, 17, 16, 16, 13, 13, 13],
       [16, 11, 17, 18, 10, 10, 12, 11, 12],
       [10, 10, 12, 18, 18, 19, 19, 18, 15],
       [15, 19, 17, 16, 15, 11, 10, 13, 16]])

In [4]:
b = a > 15
b.astype(np.int) # True는 1로, False는 0으로 바꿔줌

array([[0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1]])

### fancy index
- array를 index value로 사용

In [5]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,2,3,1]) # 반드시 integer로 선언
a[b] # bracket index

array([2, 2, 4, 6, 8, 4])

In [6]:
a.take(b) # take 함수, 같은 효과 

array([2, 2, 4, 6, 8, 4])

In [7]:
x = np.array([[1,4],[9,16]])
y = np.array([0,0,1,1,0])
z = np.array([0,1,1,1,1])

x[y,z]

array([ 1,  4, 16, 16,  4])