### np.where

In [5]:
a = np.array([1,2,3])

In [3]:
np.where(a > 0, 3, 2) # np.where(조건, True시 반환값, False시 반환값)

array([3, 3, 3])

In [4]:
np.where(a>1) # index 값 반환

(array([1, 2], dtype=int64),)

 ### argmax & argmin

In [7]:
a = np.array([1,2,3,4,5,8,78,23,31])
np.argmax(a), np.argmin(a) # index값 반환

(6, 0)

In [9]:
b = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
b

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [10]:
np.argmax(b, axis=1), np.argmin(b, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))